# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    tty: true
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - adminer
      - db
    environment: 
      - HOST_DB=db
    command: npm run dev

  db:
    image: postgres
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./DB/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ExampleDB

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db
